package com.davisy.service;

import java.io.FileOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import com.davisy.entity.User;

import jakarta.activation.DataSource;
import jakarta.activation.FileDataSource;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;

@Service
public class EmailService {

	private final JavaMailSender mailSender;

	public EmailService(JavaMailSender mailSender) {
		this.mailSender = mailSender;
	}
	
	public void sendHtmlEmailToUserIsBan(String email) throws MessagingException {
		String fromEmail = "destiny.davisy@gmail.com";

		String body = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "        /* What it does: Remove spaces around the email design added by some email clients. */\r\n"
				+ "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\r\n"
				+ "        html,\r\n"
				+ "body {\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    height: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "    background: #f1f1f1;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops email clients resizing small text. */\r\n"
				+ "* {\r\n"
				+ "    -ms-text-size-adjust: 100%;\r\n"
				+ "    -webkit-text-size-adjust: 100%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Centers email on Android 4.4 */\r\n"
				+ "div[style*=\"margin: 16px 0\"] {\r\n"
				+ "    margin: 0 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops Outlook from adding extra spacing to tables. */\r\n"
				+ "table,\r\n"
				+ "td {\r\n"
				+ "    mso-table-lspace: 0pt !important;\r\n"
				+ "    mso-table-rspace: 0pt !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Fixes webkit padding issue. */\r\n"
				+ "table {\r\n"
				+ "    border-spacing: 0 !important;\r\n"
				+ "    border-collapse: collapse !important;\r\n"
				+ "    table-layout: fixed !important;\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Uses a better rendering method when resizing images in IE. */\r\n"
				+ "img {\r\n"
				+ "    -ms-interpolation-mode:bicubic;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\r\n"
				+ "a {\r\n"
				+ "    text-decoration: none;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: A work-around for email clients meddling in triggered links. */\r\n"
				+ "*[x-apple-data-detectors],  /* iOS */\r\n"
				+ ".unstyle-auto-detected-links *,\r\n"
				+ ".aBn {\r\n"
				+ "    border-bottom: 0 !important;\r\n"
				+ "    cursor: default !important;\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\r\n"
				+ ".a6S {\r\n"
				+ "    display: none !important;\r\n"
				+ "    opacity: 0.01 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from changing the text color in conversation threads. */\r\n"
				+ ".im {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* If the above doesn't work, add a .g-img class to any image in question. */\r\n"
				+ "img.g-img + div {\r\n"
				+ "    display: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\r\n"
				+ "/* Create one of these media queries for each additional viewport size you'd like to fix */\r\n"
				+ "\r\n"
				+ "/* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 320px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6, 6S, 7, 8, and X */\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 375px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6+, 7+, and 8+ */\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 414px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : END -->\r\n"
				+ "\r\n"
				+ "    <!-- Progressive Enhancements : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "	    .primary{\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "}\r\n"
				+ ".bg_white{\r\n"
				+ "	background: #ffffff;\r\n"
				+ "}\r\n"
				+ ".bg_light{\r\n"
				+ "	background: #fafafa;\r\n"
				+ "}\r\n"
				+ ".bg_black{\r\n"
				+ "	background: #000000;\r\n"
				+ "}\r\n"
				+ ".bg_dark{\r\n"
				+ "	background: rgba(0,0,0,.8);\r\n"
				+ "}\r\n"
				+ ".email-section{\r\n"
				+ "	padding:2.5em;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*BUTTON*/\r\n"
				+ ".btn{\r\n"
				+ "	padding: 10px 15px;\r\n"
				+ "	display: inline-block;\r\n"
				+ "}\r\n"
				+ ".btn.btn-primary{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #ffffff;\r\n"
				+ "	color: #000000;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white-outline{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 1px solid #fff;\r\n"
				+ "	color: #fff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-black-outline{\r\n"
				+ "	border-radius: 0px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 2px solid #000;\r\n"
				+ "	color: #000;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "h1,h2,h3,h4,h5,h6{\r\n"
				+ "	font-family: 'Times New Roman', Times, serif;\r\n"
				+ "	color: #000000;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	font-size: 15px;\r\n"
				+ "	line-height: 1.8;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table{\r\n"
				+ "}\r\n"
				+ "/*LOGO*/\r\n"
				+ "\r\n"
				+ ".logo h1{\r\n"
				+ "	margin: 0;\r\n"
				+ "}\r\n"
				+ ".logo h1 a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*HERO*/\r\n"
				+ ".hero{\r\n"
				+ "	position: relative;\r\n"
				+ "	z-index: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".hero .text{\r\n"
				+ "	color: rgba(0,0,0,.3);\r\n"
				+ "}\r\n"
				+ ".hero .text h2{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 40px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "}\r\n"
				+ ".hero .text h3{\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 300;\r\n"
				+ "}\r\n"
				+ ".hero .text h2 span{\r\n"
				+ "	font-weight: 600;\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "/*HEADING SECTION*/\r\n"
				+ ".heading-section{\r\n"
				+ "}\r\n"
				+ ".heading-section h2{\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 28px;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading{\r\n"
				+ "	margin-bottom: 20px !important;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "	position: relative;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading::after{\r\n"
				+ "	position: absolute;\r\n"
				+ "	left: 0;\r\n"
				+ "	right: 0;\r\n"
				+ "	bottom: -10px;\r\n"
				+ "	content: '';\r\n"
				+ "	width: 100%;\r\n"
				+ "	height: 2px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	margin: 0 auto;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".heading-section-white{\r\n"
				+ "	color: rgba(255,255,255,.8);\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	/* font-family:  */\r\n"
				+ "	line-height: 1;\r\n"
				+ "	padding-bottom: 0;\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".heading-section-white .subheading{\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(255,255,255,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "ul.social{\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ "ul.social li{\r\n"
				+ "	display: inline-block;\r\n"
				+ "	margin-right: 10px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*FOOTER*/\r\n"
				+ "\r\n"
				+ ".footer{\r\n"
				+ "	border-top: 1px solid rgba(0,0,0,.05);\r\n"
				+ "	color: rgba(0,0,0,.5);\r\n"
				+ "}\r\n"
				+ ".footer .heading{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 20px;\r\n"
				+ "}\r\n"
				+ ".footer ul{\r\n"
				+ "	margin: 0;\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ ".footer ul li{\r\n"
				+ "	list-style: none;\r\n"
				+ "	margin-bottom: 10px;\r\n"
				+ "}\r\n"
				+ ".footer ul li a{\r\n"
				+ "	color: rgba(0,0,0,1);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "@media screen and (max-width: 500px) {\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\r\n"
				+ "	<center style=\"width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\r\n"
				+ "          	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "          		<tr>\r\n"
				+ "          			<td class=\"logo\" style=\"text-align: center;\">\r\n"
				+ "			            <h1><a href=\"#\">Email</a></h1>\r\n"
				+ "			          </td>\r\n"
				+ "          		</tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 3em 0 2em 0;\">\r\n"
				+ "            <img src=\"https://firebasestorage.googleapis.com/v0/b/destiny-davisy.appspot.com/o/banned.png?alt=media&token=de0945b7-b98f-42a6-bcc2-00f95b37dc6b\" alt=\"\" style=\"width: 300px; max-width: 600px; height: auto; margin: auto; display: block;\">\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "				<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "            		<td>\r\n"
				+ "            			<div class=\"text\" style=\"padding: 0 2.5em; text-align: center;\">\r\n"
				+ "            				<h3>Tài khoản của bạn đã bị khóa do hành vi bị báo cáo! <br> Vui lòng liên hệ qua mail destiny.davisy@gmail.com để được hỗ trợ!</h3>\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"bg_light footer email-section\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-right: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Về chúng tôi</h3>\r\n"
				+ "                      	<p>Diễn đàn tặng đồ là một cộng đồng\r\n"
				+ "                            trực tuyến nơi mọi người có thể tặng\r\n"
				+ "                            và nhận đồ từ nhau một cách miễn\r\n"
				+ "                            phí. Diễn đàn này tạo ra\r\n"
				+ "                            một không gian trao đổi đồ hoàn toàn phi\r\n"
				+ "                            thương mại và không có sự đòi hỏi trả\r\n"
				+ "                            lại.</p>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Liên hệ</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><span class=\"text\">FPT Polytechnic Cần Thơ</span></li>\r\n"
				+ "					                <li><span class=\"text\">+ 1235 2355 98</span></a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <!-- <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Useful Links</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><a href=\"#\">Home</a></li>\r\n"
				+ "					                <li><a href=\"#\">About</a></li>\r\n"
				+ "					                <li><a href=\"#\">Services</a></li>\r\n"
				+ "					                <li><a href=\"#\">Work</a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td> -->\r\n"
				+ "        </tr><!-- end: tr -->\r\n"
				+ "        <!-- <tr>\r\n"
				+ "          <td class=\"bg_light\" style=\"text-align: center;\">\r\n"
				+ "          	<p>No longer want to receive these email? You can <a href=\"#\" style=\"color: rgba(0,0,0,.8);\">Unsubscribe here</a></p>\r\n"
				+ "          </td>\r\n"
				+ "        </tr> -->\r\n"
				+ "      </table>\r\n"
				+ "\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		// Set email properties
		helper.setFrom(fromEmail);
		helper.setTo(email);
		helper.setSubject("Subject");

		// Add the HTML body with the image attachment (embedded)
		helper.setText(body, true);
		

		// Send the email
		mailSender.send(message);

		System.out.println("Email sent successfully!");
	}

	public void sendHtmlEmailToUserIsUnBan(String email) throws MessagingException {
		String fromEmail = "destiny.davisy@gmail.com";

		String body = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "        /* What it does: Remove spaces around the email design added by some email clients. */\r\n"
				+ "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\r\n"
				+ "        html,\r\n"
				+ "body {\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    height: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "    background: #f1f1f1;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops email clients resizing small text. */\r\n"
				+ "* {\r\n"
				+ "    -ms-text-size-adjust: 100%;\r\n"
				+ "    -webkit-text-size-adjust: 100%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Centers email on Android 4.4 */\r\n"
				+ "div[style*=\"margin: 16px 0\"] {\r\n"
				+ "    margin: 0 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops Outlook from adding extra spacing to tables. */\r\n"
				+ "table,\r\n"
				+ "td {\r\n"
				+ "    mso-table-lspace: 0pt !important;\r\n"
				+ "    mso-table-rspace: 0pt !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Fixes webkit padding issue. */\r\n"
				+ "table {\r\n"
				+ "    border-spacing: 0 !important;\r\n"
				+ "    border-collapse: collapse !important;\r\n"
				+ "    table-layout: fixed !important;\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Uses a better rendering method when resizing images in IE. */\r\n"
				+ "img {\r\n"
				+ "    -ms-interpolation-mode:bicubic;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\r\n"
				+ "a {\r\n"
				+ "    text-decoration: none;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: A work-around for email clients meddling in triggered links. */\r\n"
				+ "*[x-apple-data-detectors],  /* iOS */\r\n"
				+ ".unstyle-auto-detected-links *,\r\n"
				+ ".aBn {\r\n"
				+ "    border-bottom: 0 !important;\r\n"
				+ "    cursor: default !important;\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\r\n"
				+ ".a6S {\r\n"
				+ "    display: none !important;\r\n"
				+ "    opacity: 0.01 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from changing the text color in conversation threads. */\r\n"
				+ ".im {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* If the above doesn't work, add a .g-img class to any image in question. */\r\n"
				+ "img.g-img + div {\r\n"
				+ "    display: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\r\n"
				+ "/* Create one of these media queries for each additional viewport size you'd like to fix */\r\n"
				+ "\r\n"
				+ "/* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 320px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6, 6S, 7, 8, and X */\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 375px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6+, 7+, and 8+ */\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 414px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : END -->\r\n"
				+ "\r\n"
				+ "    <!-- Progressive Enhancements : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "	    .primary{\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "}\r\n"
				+ ".bg_white{\r\n"
				+ "	background: #ffffff;\r\n"
				+ "}\r\n"
				+ ".bg_light{\r\n"
				+ "	background: #fafafa;\r\n"
				+ "}\r\n"
				+ ".bg_black{\r\n"
				+ "	background: #000000;\r\n"
				+ "}\r\n"
				+ ".bg_dark{\r\n"
				+ "	background: rgba(0,0,0,.8);\r\n"
				+ "}\r\n"
				+ ".email-section{\r\n"
				+ "	padding:2.5em;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*BUTTON*/\r\n"
				+ ".btn{\r\n"
				+ "	padding: 10px 15px;\r\n"
				+ "	display: inline-block;\r\n"
				+ "}\r\n"
				+ ".btn.btn-primary{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #ffffff;\r\n"
				+ "	color: #000000;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white-outline{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 1px solid #fff;\r\n"
				+ "	color: #fff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-black-outline{\r\n"
				+ "	border-radius: 0px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 2px solid #000;\r\n"
				+ "	color: #000;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "h1,h2,h3,h4,h5,h6{\r\n"
				+ "	font-family: 'Times New Roman', Times, serif;\r\n"
				+ "	color: #000000;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	font-size: 15px;\r\n"
				+ "	line-height: 1.8;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table{\r\n"
				+ "}\r\n"
				+ "/*LOGO*/\r\n"
				+ "\r\n"
				+ ".logo h1{\r\n"
				+ "	margin: 0;\r\n"
				+ "}\r\n"
				+ ".logo h1 a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*HERO*/\r\n"
				+ ".hero{\r\n"
				+ "	position: relative;\r\n"
				+ "	z-index: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".hero .text{\r\n"
				+ "	color: rgba(0,0,0,.3);\r\n"
				+ "}\r\n"
				+ ".hero .text h2{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 40px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "}\r\n"
				+ ".hero .text h3{\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 300;\r\n"
				+ "}\r\n"
				+ ".hero .text h2 span{\r\n"
				+ "	font-weight: 600;\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "/*HEADING SECTION*/\r\n"
				+ ".heading-section{\r\n"
				+ "}\r\n"
				+ ".heading-section h2{\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 28px;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading{\r\n"
				+ "	margin-bottom: 20px !important;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "	position: relative;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading::after{\r\n"
				+ "	position: absolute;\r\n"
				+ "	left: 0;\r\n"
				+ "	right: 0;\r\n"
				+ "	bottom: -10px;\r\n"
				+ "	content: '';\r\n"
				+ "	width: 100%;\r\n"
				+ "	height: 2px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	margin: 0 auto;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".heading-section-white{\r\n"
				+ "	color: rgba(255,255,255,.8);\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	/* font-family:  */\r\n"
				+ "	line-height: 1;\r\n"
				+ "	padding-bottom: 0;\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".heading-section-white .subheading{\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(255,255,255,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "ul.social{\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ "ul.social li{\r\n"
				+ "	display: inline-block;\r\n"
				+ "	margin-right: 10px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*FOOTER*/\r\n"
				+ "\r\n"
				+ ".footer{\r\n"
				+ "	border-top: 1px solid rgba(0,0,0,.05);\r\n"
				+ "	color: rgba(0,0,0,.5);\r\n"
				+ "}\r\n"
				+ ".footer .heading{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 20px;\r\n"
				+ "}\r\n"
				+ ".footer ul{\r\n"
				+ "	margin: 0;\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ ".footer ul li{\r\n"
				+ "	list-style: none;\r\n"
				+ "	margin-bottom: 10px;\r\n"
				+ "}\r\n"
				+ ".footer ul li a{\r\n"
				+ "	color: rgba(0,0,0,1);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "@media screen and (max-width: 500px) {\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\r\n"
				+ "	<center style=\"width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\r\n"
				+ "          	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "          		<tr>\r\n"
				+ "          			<td class=\"logo\" style=\"text-align: center;\">\r\n"
				+ "			            <h1><a href=\"#\">Email</a></h1>\r\n"
				+ "			          </td>\r\n"
				+ "          		</tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 3em 0 2em 0;\">\r\n"
				+ "            <img src=\"https://firebasestorage.googleapis.com/v0/b/destiny-davisy.appspot.com/o/94a122c75a43bbc885b07f655777636a.jpg?alt=media&token=22e82ac7-fcf3-4756-8e06-63cc06765fa1\" alt=\"\" style=\"width: 300px; max-width: 600px; height: auto; margin: auto; display: block;\">\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "				<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "            		<td>\r\n"
				+ "            			<div class=\"text\" style=\"padding: 0 2.5em; text-align: center;\">\r\n"
				+ "            				<h3>Tài khoản của bạn đã được mở khóa!</h3>\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"bg_light footer email-section\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-right: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Về chúng tôi</h3>\r\n"
				+ "                      	<p>Diễn đàn tặng đồ là một cộng đồng\r\n"
				+ "                            trực tuyến nơi mọi người có thể tặng\r\n"
				+ "                            và nhận đồ từ nhau một cách miễn\r\n"
				+ "                            phí. Diễn đàn này tạo ra\r\n"
				+ "                            một không gian trao đổi đồ hoàn toàn phi\r\n"
				+ "                            thương mại và không có sự đòi hỏi trả\r\n"
				+ "                            lại.</p>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Liên hệ</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><span class=\"text\">FPT Polytechnic Cần Thơ</span></li>\r\n"
				+ "					                <li><span class=\"text\">+ 1235 2355 98</span></a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <!-- <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Useful Links</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><a href=\"#\">Home</a></li>\r\n"
				+ "					                <li><a href=\"#\">About</a></li>\r\n"
				+ "					                <li><a href=\"#\">Services</a></li>\r\n"
				+ "					                <li><a href=\"#\">Work</a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td> -->\r\n"
				+ "        </tr><!-- end: tr -->\r\n"
				+ "        <!-- <tr>\r\n"
				+ "          <td class=\"bg_light\" style=\"text-align: center;\">\r\n"
				+ "          	<p>No longer want to receive these email? You can <a href=\"#\" style=\"color: rgba(0,0,0,.8);\">Unsubscribe here</a></p>\r\n"
				+ "          </td>\r\n"
				+ "        </tr> -->\r\n"
				+ "      </table>\r\n"
				+ "\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		// Set email properties
		helper.setFrom(fromEmail);
		helper.setTo(email);
		helper.setSubject("Subject");

		// Add the HTML body with the image attachment (embedded)
		helper.setText(body, true);
		

		// Send the email
		mailSender.send(message);

		System.out.println("Email sent successfully!");
	}
	
	public void sendEmailWithImage(List<byte[]> imageBytesList, User user, String seat, int tickets,
			int money) throws MessagingException, IOException {
		List<String> tempImagePaths = new ArrayList<>();
		String[] s = seat.split(",");
		// Save the image to a temporary file
		for (int i = 0; i < imageBytesList.size(); i++) {
			byte[] imageBytes = imageBytesList.get(i);

			// Save the image to a temporary file
			String tempImagePath = "temp_image" + i + ".png";
			try (FileOutputStream fos = new FileOutputStream(tempImagePath)) {
				fos.write(imageBytes);
			}

			tempImagePaths.add(tempImagePath);

			// Send email with the image embedded in HTML
			//sendHtmlEmail(tempImagePath, user, "uiu", s[i], tickets, money);
			if (tempImagePath != null) {
				java.io.File tempFile = new java.io.File(tempImagePath);
				if (tempFile.exists()) {
					tempFile.delete();
				}
			}
		}

		// Delete the temporary image file
		// (You can also store the image in a different location or avoid creating a
		// file altogether if not needed)

	}

	public void sendHtmlEmail(String url,String email) throws MessagingException {
		String fromEmail = "destiny.davisy@gmail.com";

		String body = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "        /* What it does: Remove spaces around the email design added by some email clients. */\r\n"
				+ "        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */\r\n"
				+ "        html,\r\n"
				+ "body {\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    height: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "    background: #f1f1f1;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops email clients resizing small text. */\r\n"
				+ "* {\r\n"
				+ "    -ms-text-size-adjust: 100%;\r\n"
				+ "    -webkit-text-size-adjust: 100%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Centers email on Android 4.4 */\r\n"
				+ "div[style*=\"margin: 16px 0\"] {\r\n"
				+ "    margin: 0 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops Outlook from adding extra spacing to tables. */\r\n"
				+ "table,\r\n"
				+ "td {\r\n"
				+ "    mso-table-lspace: 0pt !important;\r\n"
				+ "    mso-table-rspace: 0pt !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Fixes webkit padding issue. */\r\n"
				+ "table {\r\n"
				+ "    border-spacing: 0 !important;\r\n"
				+ "    border-collapse: collapse !important;\r\n"
				+ "    table-layout: fixed !important;\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Uses a better rendering method when resizing images in IE. */\r\n"
				+ "img {\r\n"
				+ "    -ms-interpolation-mode:bicubic;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\r\n"
				+ "a {\r\n"
				+ "    text-decoration: none;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: A work-around for email clients meddling in triggered links. */\r\n"
				+ "*[x-apple-data-detectors],  /* iOS */\r\n"
				+ ".unstyle-auto-detected-links *,\r\n"
				+ ".aBn {\r\n"
				+ "    border-bottom: 0 !important;\r\n"
				+ "    cursor: default !important;\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\r\n"
				+ ".a6S {\r\n"
				+ "    display: none !important;\r\n"
				+ "    opacity: 0.01 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from changing the text color in conversation threads. */\r\n"
				+ ".im {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* If the above doesn't work, add a .g-img class to any image in question. */\r\n"
				+ "img.g-img + div {\r\n"
				+ "    display: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\r\n"
				+ "/* Create one of these media queries for each additional viewport size you'd like to fix */\r\n"
				+ "\r\n"
				+ "/* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 320px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6, 6S, 7, 8, and X */\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 375px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6+, 7+, and 8+ */\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 414px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : END -->\r\n"
				+ "\r\n"
				+ "    <!-- Progressive Enhancements : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "	    .primary{\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "}\r\n"
				+ ".bg_white{\r\n"
				+ "	background: #ffffff;\r\n"
				+ "}\r\n"
				+ ".bg_light{\r\n"
				+ "	background: #fafafa;\r\n"
				+ "}\r\n"
				+ ".bg_black{\r\n"
				+ "	background: #000000;\r\n"
				+ "}\r\n"
				+ ".bg_dark{\r\n"
				+ "	background: rgba(0,0,0,.8);\r\n"
				+ "}\r\n"
				+ ".email-section{\r\n"
				+ "	padding:2.5em;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*BUTTON*/\r\n"
				+ ".btn{\r\n"
				+ "	padding: 10px 15px;\r\n"
				+ "	display: inline-block;\r\n"
				+ "}\r\n"
				+ ".btn.btn-primary{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: #ffffff;\r\n"
				+ "	color: #000000;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white-outline{\r\n"
				+ "	border-radius: 5px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 1px solid #fff;\r\n"
				+ "	color: #fff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-black-outline{\r\n"
				+ "	border-radius: 0px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 2px solid #000;\r\n"
				+ "	color: #000;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "h1,h2,h3,h4,h5,h6{\r\n"
				+ "	font-family: 'Times New Roman', Times, serif;\r\n"
				+ "	color: #000000;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	font-size: 15px;\r\n"
				+ "	line-height: 1.8;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table{\r\n"
				+ "}\r\n"
				+ "/*LOGO*/\r\n"
				+ "\r\n"
				+ ".logo h1{\r\n"
				+ "	margin: 0;\r\n"
				+ "}\r\n"
				+ ".logo h1 a{\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "	font-family: 'Lato', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*HERO*/\r\n"
				+ ".hero{\r\n"
				+ "	position: relative;\r\n"
				+ "	z-index: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".hero .text{\r\n"
				+ "	color: rgba(0,0,0,.3);\r\n"
				+ "}\r\n"
				+ ".hero .text h2{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 40px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "}\r\n"
				+ ".hero .text h3{\r\n"
				+ "	font-size: 24px;\r\n"
				+ "	font-weight: 300;\r\n"
				+ "}\r\n"
				+ ".hero .text h2 span{\r\n"
				+ "	font-weight: 600;\r\n"
				+ "	color: #30e3ca;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "/*HEADING SECTION*/\r\n"
				+ ".heading-section{\r\n"
				+ "}\r\n"
				+ ".heading-section h2{\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 28px;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading{\r\n"
				+ "	margin-bottom: 20px !important;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "	position: relative;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading::after{\r\n"
				+ "	position: absolute;\r\n"
				+ "	left: 0;\r\n"
				+ "	right: 0;\r\n"
				+ "	bottom: -10px;\r\n"
				+ "	content: '';\r\n"
				+ "	width: 100%;\r\n"
				+ "	height: 2px;\r\n"
				+ "	background: #30e3ca;\r\n"
				+ "	margin: 0 auto;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".heading-section-white{\r\n"
				+ "	color: rgba(255,255,255,.8);\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	/* font-family:  */\r\n"
				+ "	line-height: 1;\r\n"
				+ "	padding-bottom: 0;\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".heading-section-white .subheading{\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(255,255,255,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "ul.social{\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ "ul.social li{\r\n"
				+ "	display: inline-block;\r\n"
				+ "	margin-right: 10px;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*FOOTER*/\r\n"
				+ "\r\n"
				+ ".footer{\r\n"
				+ "	border-top: 1px solid rgba(0,0,0,.05);\r\n"
				+ "	color: rgba(0,0,0,.5);\r\n"
				+ "}\r\n"
				+ ".footer .heading{\r\n"
				+ "	color: #000;\r\n"
				+ "	font-size: 20px;\r\n"
				+ "}\r\n"
				+ ".footer ul{\r\n"
				+ "	margin: 0;\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ ".footer ul li{\r\n"
				+ "	list-style: none;\r\n"
				+ "	margin-bottom: 10px;\r\n"
				+ "}\r\n"
				+ ".footer ul li a{\r\n"
				+ "	color: rgba(0,0,0,1);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "@media screen and (max-width: 500px) {\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #f1f1f1;\">\r\n"
				+ "	<center style=\"width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"top\" class=\"bg_white\" style=\"padding: 1em 2.5em 0 2.5em;\">\r\n"
				+ "          	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "          		<tr>\r\n"
				+ "          			<td class=\"logo\" style=\"text-align: center;\">\r\n"
				+ "			            <h1><a href=\"#\">Email</a></h1>\r\n"
				+ "			          </td>\r\n"
				+ "          		</tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 3em 0 2em 0;\">\r\n"
				+ "            <img src=\"https://firebasestorage.googleapis.com/v0/b/davitickets-2e627.appspot.com/o/email.png?alt=media&token=6f31d4c1-1a7d-4fb5-bf90-f836224f0ea6\" alt=\"\" style=\"width: 300px; max-width: 600px; height: auto; margin: auto; display: block;\">\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "				<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"padding: 2em 0 4em 0;\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "            		<td>\r\n"
				+ "            			<div class=\"text\" style=\"padding: 0 2.5em; text-align: center;\">\r\n"
				+ "            				<h3>Vui lòng xác minh email của bạn</h3>\r\n"
				+ "            				<h4>Chọn \"Xác nhận\" để hoàn tất quá trình đăng kí</h4>\r\n"
				+ "            				<p><a href=\""+url+"\" class=\"btn btn-primary\">Xác nhận</a></p>\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"bg_light footer email-section\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-right: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Về chúng tôi</h3>\r\n"
				+ "                      	<p>Diễn đàn tặng đồ là một cộng đồng\r\n"
				+ "                            trực tuyến nơi mọi người có thể tặng\r\n"
				+ "                            và nhận đồ từ nhau một cách miễn\r\n"
				+ "                            phí. Diễn đàn này tạo ra\r\n"
				+ "                            một không gian trao đổi đồ hoàn toàn phi\r\n"
				+ "                            thương mại và không có sự đòi hỏi trả\r\n"
				+ "                            lại.</p>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Liên hệ</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><span class=\"text\">FPT Polytechnic Cần Thơ</span></li>\r\n"
				+ "					                <li><span class=\"text\">+ 1235 2355 98</span></a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <!-- <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-left: 10px;\">\r\n"
				+ "                      	<h3 class=\"heading\">Useful Links</h3>\r\n"
				+ "                      	<ul>\r\n"
				+ "					                <li><a href=\"#\">Home</a></li>\r\n"
				+ "					                <li><a href=\"#\">About</a></li>\r\n"
				+ "					                <li><a href=\"#\">Services</a></li>\r\n"
				+ "					                <li><a href=\"#\">Work</a></li>\r\n"
				+ "					              </ul>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td> -->\r\n"
				+ "        </tr><!-- end: tr -->\r\n"
				+ "        <!-- <tr>\r\n"
				+ "          <td class=\"bg_light\" style=\"text-align: center;\">\r\n"
				+ "          	<p>No longer want to receive these email? You can <a href=\"#\" style=\"color: rgba(0,0,0,.8);\">Unsubscribe here</a></p>\r\n"
				+ "          </td>\r\n"
				+ "        </tr> -->\r\n"
				+ "      </table>\r\n"
				+ "\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		// Set email properties
		helper.setFrom(fromEmail);
		helper.setTo(email);
		helper.setSubject("Subject");

		// Add the HTML body with the image attachment (embedded)
		helper.setText(body, true);
		

		// Send the email
		mailSender.send(message);

		System.out.println("Email sent successfully!");
	}
	public void sendHtmlEmailContact(String fullname,String email,String subject, String description) throws MessagingException {
		String fromEmail = "destiny.davisy@gmail.com";

		String body = "<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"utf-8\"> <!-- utf-8 works for most cases -->\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width\"> <!-- Forcing initial-scale shouldn't be necessary -->\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\"> <!-- Use the latest (edge) version of IE rendering engine -->\r\n"
				+ "    <meta name=\"x-apple-disable-message-reformatting\">  <!-- Disable auto-scale in iOS 10 Mail entirely -->\r\n"
				+ "    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->\r\n"
				+ "\r\n"
				+ "    <link href=\"https://fonts.googleapis.com/css?family=Work+Sans:200,300,400,500,600,700\" rel=\"stylesheet\">\r\n"
				+ "\r\n"
				+ "    <!-- CSS Reset : BEGIN -->\r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "        html,\r\n"
				+ "body {\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "    padding: 0 !important;\r\n"
				+ "    height: 100% !important;\r\n"
				+ "    width: 100% !important;\r\n"
				+ "    background: #f1f1f1;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops email clients resizing small text. */\r\n"
				+ "* {\r\n"
				+ "    -ms-text-size-adjust: 100%;\r\n"
				+ "    -webkit-text-size-adjust: 100%;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Centers email on Android 4.4 */\r\n"
				+ "div[style*=\"margin: 16px 0\"] {\r\n"
				+ "    margin: 0 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Stops Outlook from adding extra spacing to tables. */\r\n"
				+ "table,\r\n"
				+ "td {\r\n"
				+ "    mso-table-lspace: 0pt !important;\r\n"
				+ "    mso-table-rspace: 0pt !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Fixes webkit padding issue. */\r\n"
				+ "table {\r\n"
				+ "    border-spacing: 0 !important;\r\n"
				+ "    border-collapse: collapse !important;\r\n"
				+ "    table-layout: fixed !important;\r\n"
				+ "    margin: 0 auto !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Uses a better rendering method when resizing images in IE. */\r\n"
				+ "img {\r\n"
				+ "    -ms-interpolation-mode:bicubic;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */\r\n"
				+ "a {\r\n"
				+ "    text-decoration: none;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: A work-around for email clients meddling in triggered links. */\r\n"
				+ "*[x-apple-data-detectors],  /* iOS */\r\n"
				+ ".unstyle-auto-detected-links *,\r\n"
				+ ".aBn {\r\n"
				+ "    border-bottom: 0 !important;\r\n"
				+ "    cursor: default !important;\r\n"
				+ "    color: inherit !important;\r\n"
				+ "    text-decoration: none !important;\r\n"
				+ "    font-size: inherit !important;\r\n"
				+ "    font-family: inherit !important;\r\n"
				+ "    font-weight: inherit !important;\r\n"
				+ "    line-height: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */\r\n"
				+ ".a6S {\r\n"
				+ "    display: none !important;\r\n"
				+ "    opacity: 0.01 !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Prevents Gmail from changing the text color in conversation threads. */\r\n"
				+ ".im {\r\n"
				+ "    color: inherit !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* If the above doesn't work, add a .g-img class to any image in question. */\r\n"
				+ "img.g-img + div {\r\n"
				+ "    display: none !important;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */\r\n"
				+ "/* Create one of these media queries for each additional viewport size you'd like to fix */\r\n"
				+ "/* iPhone 4, 4S, 5, 5S, 5C, and 5SE */\r\n"
				+ "@media only screen and (min-device-width: 320px) and (max-device-width: 374px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 320px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6, 6S, 7, 8, and X */\r\n"
				+ "@media only screen and (min-device-width: 375px) and (max-device-width: 413px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 375px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "/* iPhone 6+, 7+, and 8+ */\r\n"
				+ "@media only screen and (min-device-width: 414px) {\r\n"
				+ "    u ~ div .email-container {\r\n"
				+ "        min-width: 414px !important;\r\n"
				+ "    }\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "  \r\n"
				+ "    <style>\r\n"
				+ "\r\n"
				+ "	    .primary{\r\n"
				+ "	background: #448ef6;\r\n"
				+ "}\r\n"
				+ ".bg_white{\r\n"
				+ "	background: #ffffff;\r\n"
				+ "}\r\n"
				+ ".bg_light{\r\n"
				+ "	background: #fafafa;\r\n"
				+ "}\r\n"
				+ ".bg_black{\r\n"
				+ "	background: #000000;\r\n"
				+ "}\r\n"
				+ ".bg_dark{\r\n"
				+ "	background: rgba(0,0,0,.8);\r\n"
				+ "}\r\n"
				+ ".email-section{\r\n"
				+ "	padding:2.5em;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*BUTTON*/\r\n"
				+ ".btn{\r\n"
				+ "	padding: 5px 15px;\r\n"
				+ "	display: inline-block;\r\n"
				+ "}\r\n"
				+ ".btn.btn-primary{\r\n"
				+ "	border-radius: 30px;\r\n"
				+ "	background: #448ef6;\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white{\r\n"
				+ "	border-radius: 30px;\r\n"
				+ "	background: #ffffff;\r\n"
				+ "	color: #000000;\r\n"
				+ "}\r\n"
				+ ".btn.btn-white-outline{\r\n"
				+ "	border-radius: 30px;\r\n"
				+ "	background: transparent;\r\n"
				+ "	border: 1px solid #fff;\r\n"
				+ "	color: #fff;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "h1,h2,h3,h4,h5,h6{\r\n"
				+ "	font-family: 'Work Sans', sans-serif;\r\n"
				+ "	color: #000000;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "body{\r\n"
				+ "	font-family: 'Work Sans', sans-serif;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "	font-size: 15px;\r\n"
				+ "	line-height: 1.8;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "a{\r\n"
				+ "	color: #448ef6;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "table{\r\n"
				+ "}\r\n"
				+ "/*LOGO*/\r\n"
				+ "\r\n"
				+ ".logo h1{\r\n"
				+ "	margin: 0;\r\n"
				+ "}\r\n"
				+ ".logo h1 a{\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 20px;\r\n"
				+ "	font-weight: 700;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	font-family: 'Poppins', sans-serif;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".navigation{\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ ".navigation li{\r\n"
				+ "	list-style: none;\r\n"
				+ "	display: inline-block;;\r\n"
				+ "	margin-left: 5px;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	font-weight: 500;\r\n"
				+ "}\r\n"
				+ ".navigation li a{\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*HERO*/\r\n"
				+ ".hero{\r\n"
				+ "	position: relative;\r\n"
				+ "	z-index: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".hero .overlay{\r\n"
				+ "	position: absolute;\r\n"
				+ "	top: 0;\r\n"
				+ "	left: 0;\r\n"
				+ "	right: 0;\r\n"
				+ "	bottom: 0;\r\n"
				+ "	content: '';\r\n"
				+ "	width: 100%;\r\n"
				+ "	background: #000000;\r\n"
				+ "	z-index: -1;\r\n"
				+ "	opacity: .3;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".hero .text{\r\n"
				+ "	color: rgba(255,255,255,.9);\r\n"
				+ "}\r\n"
				+ ".hero .text h2{\r\n"
				+ "	color: #fff;\r\n"
				+ "	font-size: 50px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "	font-weight: 300;\r\n"
				+ "	line-height: 1;\r\n"
				+ "}\r\n"
				+ ".hero .text h2 span{\r\n"
				+ "	font-weight: 600;\r\n"
				+ "	color: #448ef6;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "/*HEADING SECTION*/\r\n"
				+ ".heading-section{\r\n"
				+ "}\r\n"
				+ ".heading-section h2{\r\n"
				+ "	color: #000000;\r\n"
				+ "	font-size: 28px;\r\n"
				+ "	margin-top: 0;\r\n"
				+ "	line-height: 1.4;\r\n"
				+ "	font-weight: 400;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading{\r\n"
				+ "	margin-bottom: 20px !important;\r\n"
				+ "	display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(0,0,0,.4);\r\n"
				+ "	position: relative;\r\n"
				+ "}\r\n"
				+ ".heading-section .subheading::after{\r\n"
				+ "	position: absolute;\r\n"
				+ "	left: 0;\r\n"
				+ "	right: 0;\r\n"
				+ "	bottom: -10px;\r\n"
				+ "	content: '';\r\n"
				+ "	width: 100%;\r\n"
				+ "	height: 2px;\r\n"
				+ "	background: #448ef6;\r\n"
				+ "	margin: 0 auto;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ ".heading-section-white{\r\n"
				+ "	color: rgba(255,255,255,.8);\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	\r\n"
				+ "	line-height : 1;\r\n"
				+ "	padding-bottom: 0;\r\n"
				+ "}\r\n"
				+ ".heading-section-white h2{\r\n"
				+ "	color: #ffffff;\r\n"
				+ "}\r\n"
				+ ".heading-section-white .subheading{\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "display: inline-block;\r\n"
				+ "	font-size: 13px;\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	letter-spacing: 2px;\r\n"
				+ "	color: rgba(255,255,255,.4);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "/*BLOG*/\r\n"
				+ ".text-services .meta{\r\n"
				+ "	text-transform: uppercase;\r\n"
				+ "	font-size: 14px;\r\n"
				+ "	margin-bottom: 0;\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "/*FOOTER*/\r\n"
				+ "\r\n"
				+ ".footer{\r\n"
				+ "	color: rgba(255,255,255,.5);\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ ".footer .heading{\r\n"
				+ "	color: #ffffff;\r\n"
				+ "	font-size: 20px;\r\n"
				+ "}\r\n"
				+ ".footer ul{\r\n"
				+ "	margin: 0;\r\n"
				+ "	padding: 0;\r\n"
				+ "}\r\n"
				+ ".footer ul li{\r\n"
				+ "	list-style: none;\r\n"
				+ "	margin-bottom: 10px;\r\n"
				+ "}\r\n"
				+ ".footer ul li a{\r\n"
				+ "	color: rgba(255,255,255,1);\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "@media screen and (max-width: 500px) {\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "}\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "    </style>\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "</head>\r\n"
				+ "\r\n"
				+ "<body width=\"100%\" style=\"margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #222222;\">\r\n"
				+ "	<center style=\"width: 100%; background-color: #f1f1f1;\">\r\n"
				+ "    <div style=\"display: none; font-size: 1px;max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden; mso-hide: all; font-family: sans-serif;\">\r\n"
				+ "      &zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;&zwnj;&nbsp;\r\n"
				+ "    </div>\r\n"
				+ "    <div style=\"max-width: 600px; margin: 0 auto;\" class=\"email-container\">\r\n"
				+ "    	<!-- BEGIN BODY -->\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	\r\n"
				+ "	      <tr>\r\n"
				+ "          <td valign=\"middle\" class=\"hero bg_white\" style=\"background-image: url(images/bg_1.jpg); background-size: cover; height: 400px;\">\r\n"
				+ "          	<div class=\"overlay\"></div>\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "            		<td>\r\n"
				+ "            			<div class=\"text\" style=\"padding: 0 4em; text-align: center;\">\r\n"
				+ "            				<h2>Phản hồi của người dùng</h2>\r\n"
				+ "            				\r\n"
				+ "            			</div>\r\n"
				+ "            		</td>\r\n"
				+ "            	</tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "	      </tr><!-- end tr -->\r\n"
				+ "	      <tr>\r\n"
				+ "	        <td class=\"bg_white email-section\">\r\n"
				+ "	        	<div class=\"heading-section\" style=\"text-align: center; padding: 0 30px;\">\r\n"
				+ "	          	<h2>"+fullname+"</h2>\r\n"
				+ "	          	<p>"+email+"</p>\r\n"
				+ "	        	</div>\r\n"
				+ "	        	<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
				+ "	        		<tr>\r\n"
				+ "	              <h3>Nội dung phản hồi :</h3> <p>"+description+"</p>\r\n"
				+ "              </tr>\r\n"
				+ "              <tr>\r\n"
				+ "	              <td valign=\"top\" width=\"50%\" style=\"padding-top: 20px; padding-right: 10px;\">\r\n"
				+ "	               \r\n"
				+ "	              </td>\r\n"
				+ "	              <td valign=\"top\" width=\"50%\" style=\"padding-top: 20px; padding-left: 10px;\">\r\n"
				+ "	               \r\n"
				+ "	              </td>\r\n"
				+ "              </tr>\r\n"
				+ "              <tr>\r\n"
				+ "	              <td valign=\"top\" width=\"50%\" style=\"padding-top: 20px; padding-right: 10px;\">\r\n"
				+ "	                \r\n"
				+ "	              </td>\r\n"
				+ "	              <td valign=\"top\" width=\"50%\" style=\"padding-top: 20px; padding-left: 10px;\">\r\n"
				+ "	               \r\n"
				+ "	              </td>\r\n"
				+ "              </tr>\r\n"
				+ "          	</table>\r\n"
				+ "          </td>\r\n"
				+ "</tr><!-- end: tr -->\r\n"
				+ "      <!-- 1 Column Text + Button : END -->\r\n"
				+ "      </table>\r\n"
				+ "      <table align=\"center\" role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\" style=\"margin: auto;\">\r\n"
				+ "      	<tr>\r\n"
				+ "          <td valign=\"middle\" class=\"bg_black footer email-section\">\r\n"
				+ "            <table>\r\n"
				+ "            	<tr>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                      <td style=\"text-align: left; padding-right: 10px;\">\r\n"
				+ "                        <h3 class=\"heading\">Về chúng tôi</h3>\r\n"
				+ "                        <p>Diễn đàn tặng đồ là một cộng đồng\r\n"
				+ "                          trực tuyến nơi mọi người có thể tặng\r\n"
				+ "                          và nhận đồ từ nhau một cách miễn\r\n"
				+ "                          phí. Diễn đàn này tạo ra\r\n"
				+ "                          một không gian trao đổi đồ hoàn toàn phi\r\n"
				+ "                          thương mại và không có sự đòi hỏi trả\r\n"
				+ "                          lại.</p>\r\n"
				+ "                      </td>\r\n"
				+ "                    </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                   \r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "                <td valign=\"top\" width=\"33.333%\" style=\"padding-top: 20px;\">\r\n"
				+ "                  <table role=\"presentation\" cellspacing=\"0\" cellpadding=\"0\" border=\"0\" width=\"100%\">\r\n"
				+ "                    <tr>\r\n"
				+ "                        <td style=\"text-align: left; padding-left: 5px; padding-right: 5px;\">\r\n"
				+ "                            <h3 class=\"heading\">Contact Info</h3>\r\n"
				+ "                            <ul>\r\n"
				+ "                                <li><span class=\"text\">FPT Polytechnic Cần Thơ</span></li>\r\n"
				+ "                                <li><span class=\"text\">+ 1235 2355 98</span></a></li>\r\n"
				+ "                              </ul>\r\n"
				+ "                        </td>\r\n"
				+ "                      </tr>\r\n"
				+ "                  </table>\r\n"
				+ "                </td>\r\n"
				+ "              </tr>\r\n"
				+ "            </table>\r\n"
				+ "          </td>\r\n"
				+ "        </tr><!-- end: tr -->\r\n"
				+ "        <tr>\r\n"
				+ "        	<td valign=\"middle\" class=\"bg_black footer email-section\">\r\n"
				+ "        	\r\n"
				+ "        	</td>\r\n"
				+ "        </tr>\r\n"
				+ "      </table>\r\n"
				+ "\r\n"
				+ "    </div>\r\n"
				+ "  </center>\r\n"
				+ "</body>\r\n"
				+ "</html>";
		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		// Set email properties
		helper.setFrom(fromEmail);
		helper.setTo(fromEmail);
		helper.setSubject(subject);

		// Add the HTML body with the image attachment (embedded)
		helper.setText(body, true);
		

		// Send the email
		mailSender.send(message);

		System.out.println("Email sent successfully!");
	}
	
	
	public void sendCodeMail(String code,String email) throws MessagingException {
		String fromEmail = "destiny.davisy@gmail.com";

		String body = code+" là mã xác nhận của bạn, mã sẽ hết hiệu lực sau 5 phút";
		MimeMessage message = mailSender.createMimeMessage();
		MimeMessageHelper helper = new MimeMessageHelper(message, true);

		// Set email properties
		helper.setFrom(fromEmail);
		helper.setTo(email);
		helper.setSubject("Subject");

		// Add the HTML body with the image attachment (embedded)
		helper.setText(body, true);
		

		// Send the email
		mailSender.send(message);

		System.out.println("Email sent successfully!");
	}
}